"""
This type stub file was generated by pyright.
"""

import collections
import grpc

"""Internal utilities for gRPC Python."""
_LOGGER = ...
_DONE_CALLBACK_EXCEPTION_LOG_MESSAGE = ...
class RpcMethodHandler(collections.namedtuple('_RpcMethodHandler', ('request_streaming', 'response_streaming', 'request_deserializer', 'response_serializer', 'unary_unary', 'unary_stream', 'stream_unary', 'stream_stream')), grpc.RpcMethodHandler):
    ...


class DictionaryGenericHandler(grpc.ServiceRpcHandler):
    def __init__(self, service, method_handlers) -> None:
        ...
    
    def service_name(self): # -> Unknown:
        ...
    
    def service(self, handler_call_details): # -> _V@iteritems | None:
        ...
    


class _ChannelReadyFuture(grpc.Future):
    def __init__(self, channel) -> None:
        ...
    
    def cancel(self): # -> bool:
        ...
    
    def cancelled(self): # -> bool:
        ...
    
    def running(self): # -> bool:
        ...
    
    def done(self): # -> bool:
        ...
    
    def result(self, timeout=...): # -> None:
        ...
    
    def exception(self, timeout=...): # -> None:
        ...
    
    def traceback(self, timeout=...): # -> None:
        ...
    
    def add_done_callback(self, fn): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


def channel_ready_future(channel): # -> _ChannelReadyFuture:
    ...

