"""
This type stub file was generated by pyright.
"""

import collections
import grpc

"""
This type stub file was generated by pyright.
"""
_LOGGER = ...
_DONE_CALLBACK_EXCEPTION_LOG_MESSAGE = ...
class RpcMethodHandler(collections.namedtuple('_RpcMethodHandler', ('request_streaming', 'response_streaming', 'request_deserializer', 'response_serializer', 'unary_unary', 'unary_stream', 'stream_unary', 'stream_stream')), grpc.RpcMethodHandler):
    ...


class DictionaryGenericHandler(grpc.ServiceRpcHandler):
    def __init__(self, service, method_handlers) -> None:
        ...
    
    def service_name(self):
        ...
    
    def service(self, handler_call_details):
        ...
    


class _ChannelReadyFuture(grpc.Future):
    def __init__(self, channel) -> None:
        ...
    
    def cancel(self):
        ...
    
    def cancelled(self):
        ...
    
    def running(self):
        ...
    
    def done(self):
        ...
    
    def result(self, timeout=...):
        ...
    
    def exception(self, timeout=...):
        ...
    
    def traceback(self, timeout=...):
        ...
    
    def add_done_callback(self, fn):
        ...
    
    def start(self):
        ...
    
    def __del__(self):
        ...
    


def channel_ready_future(channel):
    ...

