"""
This type stub file was generated by pyright.
"""

V: array - like
VI: array - like
p: int
difference: math
w: (N, )
p = ...
p = ...
class provides:
   ...


the: meth
class method:
   ...


classes: <Expression>
class name:
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


