[tool.black]
line-length = 88
include = '\.py$'
exclude = '''
/(
    \.git
  | \.vscode
  | images
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
src_paths = ["notifier"]

[tool.pyright]
include = ["tracker"]
exclude = [
    "**/__pycache__",
    "tracker.egg-info",
    "images",
    "tracker/typestubs"
]
ignore = []
stubPath = "tracker/stubs"
venv = "env367"

reportMissingImports = false
reportMissingTypeStubs = false

pythonVersion = "3.7"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "tracker" }
]
