[tool.black]
target-version = ['py37']
line-length = 88
include = '\.py$'
exclude = '''
/(
    \.git
  | \.vscode
  | __pycache__
  | tracker/session_.*\.py$
)/
'''

[tool.isort]
profile = "black"
src_paths = ["tracker"]

[tool.pyright]
include = ["tracker"]
exclude = [
    ".vscode",
    "**/__pycache__",
    "stream",
    "tracker.egg-info"
]
stubPath = "./typings"
ignore = ["tracker/session_*.py"]
venv = "tracker"
venvPath = "../../../.local/virtualenvs"
pythonVersion = "3.7"
pythonPlatform = "Linux"
executionEnvironments = [
  { root = "tracker" }
]
reportMissingImports = false
reportMissingTypeStubs = true
