[tool.black]
line-length = 88
include = '\.py$'
exclude = '''
/(
    \.git
  | \.vscode
  | images
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
src_paths = ["tracker"]

[tool.pyright]
include = ["tracker"]
exclude = [
    ".vscode",
    "**/__pycache__",
    "images",
    "tracker.egg-info"
]
ignore = []
venvPath = "~/.virtualenvs"
venv = "tracker"
pythonVersion = "3.7"
pythonPlatform = "Linux"
executionEnvironments = [
  { root = "tracker" }
]
reportMissingImports = false
reportMissingTypeStubs = false
