[tool.black]
line-length = 88
include = '\.py$'
exclude = '''
/(
    \.git
  | \.vscode
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 5

[tool.pyright]
include = ["src"]
exclude = [
    "**/__pycache__",
    "src/typestubs"
]
ignore = []
stubPath = "src/stubs"
venv = "env367"

reportMissingImports = false
reportMissingTypeStubs = false

pythonVersion = "3.7"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src" }
]
