"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, TYPE_CHECKING

"""
This is part of the MSS Python's module.
Source: https://github.com/BoboTiG/python-mss
"""
if TYPE_CHECKING:
    ...
class ScreenShotError(Exception):
    """ Error handling class. """
    def __init__(self, message: str, details: Dict[str, Any] = ...) -> None:
        ...
    


