"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Tuple

"""
This is part of the MSS Python's module.
Source: https://github.com/BoboTiG/python-mss
"""
Monitor = Dict[str, int]
Monitors = List[Monitor]
Pixel = Tuple[int, int, int]
Pixels = List[Pixel]
Pos = ...
Size = ...
