"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING, Tuple

"""
This is part of the MSS Python's module.
Source: https://github.com/BoboTiG/python-mss
"""
if TYPE_CHECKING:
    ...
def to_png(data: bytes, size: Tuple[int, int], level: int = ..., output: Optional[str] = ...) -> Optional[bytes]:
    """
    Dump data to a PNG file.  If `output` is `None`, create no file but return
    the whole PNG data.

    :param bytes data: RGBRGB...RGB data.
    :param tuple size: The (width, height) pair.
    :param int level: PNG compression level.
    :param str output: Output file name.
    """
    ...

