"""
This type stub file was generated by pyright.
"""

from .glm import GammaRegressor, GeneralizedLinearRegressor, PoissonRegressor, TweedieRegressor

__all__ = ["GeneralizedLinearRegressor", "PoissonRegressor", "GammaRegressor", "TweedieRegressor"]
