# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tracker.session_pb2 as session__pb2


class SessionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFrame = channel.unary_unary(
            "/evercoinx.session.Session/SendFrame",
            request_serializer=session__pb2.FrameRequest.SerializeToString,
            response_deserializer=session__pb2.EmptyReponse.FromString,
        )


class SessionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendFrame": grpc.unary_unary_rpc_method_handler(
            servicer.SendFrame,
            request_deserializer=session__pb2.FrameRequest.FromString,
            response_serializer=session__pb2.EmptyReponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "evercoinx.session.Session", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Session(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFrame(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/evercoinx.session.Session/SendFrame",
            session__pb2.FrameRequest.SerializeToString,
            session__pb2.EmptyReponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
