# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="analyzer.proto",
    package="evercoinx.analyzer",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0e\x61nalyzer.proto\x12\x12\x65vercoinx.analyzer"\xe0\x01\n\x0c\x46rameRequest\x12\x14\n\x0cwindow_index\x18\x01 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x12\x13\n\x0bhand_number\x18\x03 \x01(\x05\x12\x11\n\thand_time\x18\x04 \x01(\t\x12,\n\ttotal_pot\x18\x05 \x01(\x0b\x32\x19.evercoinx.analyzer.Money\x12\x17\n\x0f\x64\x65\x61ler_position\x18\x06 \x01(\x05\x12\'\n\x05seats\x18\x07 \x03(\x0b\x32\x18.evercoinx.analyzer.Seat\x12\r\n\x05\x62oard\x18\x08 \x03(\t"\x0f\n\rEmptyResponse"z\n\x05Money\x12\x34\n\x08\x63urrency\x18\x01 \x01(\x0e\x32".evercoinx.analyzer.Money.Currency\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01"+\n\x08\x43urrency\x12\t\n\x05UNSET\x10\x00\x12\x08\n\x04\x45URO\x10\x01\x12\n\n\x06\x44OLLAR\x10\x02"\xa6\x02\n\x04Seat\x12\x0e\n\x06number\x18\x01 \x01(\x11\x12/\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1f.evercoinx.analyzer.Seat.Action\x12(\n\x05stake\x18\x03 \x01(\x0b\x32\x19.evercoinx.analyzer.Money\x12*\n\x07\x62\x61lance\x18\x04 \x01(\x0b\x32\x19.evercoinx.analyzer.Money\x12\x0f\n\x07playing\x18\x05 \x01(\x08"v\n\x06\x41\x63tion\x12\t\n\x05UNSET\x10\x00\x12\x07\n\x03\x42\x45T\x10\x01\x12\t\n\x05RAISE\x10\x02\x12\x08\n\x04\x43\x41LL\x10\x03\x12\x08\n\x04\x46OLD\x10\x04\x12\t\n\x05\x43HECK\x10\x05\x12\n\n\x06\x41LL_IN\x10\x06\x12\x0e\n\nSITTING_IN\x10\x07\x12\x12\n\x0eWAITING_FOR_BB\x10\x08\x32^\n\x08\x41nalyzer\x12R\n\tSendFrame\x12 .evercoinx.analyzer.FrameRequest\x1a!.evercoinx.analyzer.EmptyResponse"\x00\x62\x06proto3',
)


_MONEY_CURRENCY = _descriptor.EnumDescriptor(
    name="Currency",
    full_name="evercoinx.analyzer.Money.Currency",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="UNSET",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="EURO",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DOLLAR",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=361,
    serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_MONEY_CURRENCY)

_SEAT_ACTION = _descriptor.EnumDescriptor(
    name="Action",
    full_name="evercoinx.analyzer.Seat.Action",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="UNSET",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="BET",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="RAISE",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CALL",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="FOLD",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CHECK",
            index=5,
            number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="ALL_IN",
            index=6,
            number=6,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SITTING_IN",
            index=7,
            number=7,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="WAITING_FOR_BB",
            index=8,
            number=8,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=583,
    serialized_end=701,
)
_sym_db.RegisterEnumDescriptor(_SEAT_ACTION)


_FRAMEREQUEST = _descriptor.Descriptor(
    name="FrameRequest",
    full_name="evercoinx.analyzer.FrameRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="window_index",
            full_name="evercoinx.analyzer.FrameRequest.window_index",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="frame_index",
            full_name="evercoinx.analyzer.FrameRequest.frame_index",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="hand_number",
            full_name="evercoinx.analyzer.FrameRequest.hand_number",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="hand_time",
            full_name="evercoinx.analyzer.FrameRequest.hand_time",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="total_pot",
            full_name="evercoinx.analyzer.FrameRequest.total_pot",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="dealer_position",
            full_name="evercoinx.analyzer.FrameRequest.dealer_position",
            index=5,
            number=6,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="seats",
            full_name="evercoinx.analyzer.FrameRequest.seats",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="board",
            full_name="evercoinx.analyzer.FrameRequest.board",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=39,
    serialized_end=263,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
    name="EmptyResponse",
    full_name="evercoinx.analyzer.EmptyResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=265,
    serialized_end=280,
)


_MONEY = _descriptor.Descriptor(
    name="Money",
    full_name="evercoinx.analyzer.Money",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="currency",
            full_name="evercoinx.analyzer.Money.currency",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="amount",
            full_name="evercoinx.analyzer.Money.amount",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _MONEY_CURRENCY,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=282,
    serialized_end=404,
)


_SEAT = _descriptor.Descriptor(
    name="Seat",
    full_name="evercoinx.analyzer.Seat",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="number",
            full_name="evercoinx.analyzer.Seat.number",
            index=0,
            number=1,
            type=17,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="action",
            full_name="evercoinx.analyzer.Seat.action",
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="stake",
            full_name="evercoinx.analyzer.Seat.stake",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="balance",
            full_name="evercoinx.analyzer.Seat.balance",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="playing",
            full_name="evercoinx.analyzer.Seat.playing",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _SEAT_ACTION,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=407,
    serialized_end=701,
)

_FRAMEREQUEST.fields_by_name["total_pot"].message_type = _MONEY
_FRAMEREQUEST.fields_by_name["seats"].message_type = _SEAT
_MONEY.fields_by_name["currency"].enum_type = _MONEY_CURRENCY
_MONEY_CURRENCY.containing_type = _MONEY
_SEAT.fields_by_name["action"].enum_type = _SEAT_ACTION
_SEAT.fields_by_name["stake"].message_type = _MONEY
_SEAT.fields_by_name["balance"].message_type = _MONEY
_SEAT_ACTION.containing_type = _SEAT
DESCRIPTOR.message_types_by_name["FrameRequest"] = _FRAMEREQUEST
DESCRIPTOR.message_types_by_name["EmptyResponse"] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name["Money"] = _MONEY
DESCRIPTOR.message_types_by_name["Seat"] = _SEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameRequest = _reflection.GeneratedProtocolMessageType(
    "FrameRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _FRAMEREQUEST,
        "__module__": "analyzer_pb2"
        # @@protoc_insertion_point(class_scope:evercoinx.analyzer.FrameRequest)
    },
)
_sym_db.RegisterMessage(FrameRequest)

EmptyResponse = _reflection.GeneratedProtocolMessageType(
    "EmptyResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTYRESPONSE,
        "__module__": "analyzer_pb2"
        # @@protoc_insertion_point(class_scope:evercoinx.analyzer.EmptyResponse)
    },
)
_sym_db.RegisterMessage(EmptyResponse)

Money = _reflection.GeneratedProtocolMessageType(
    "Money",
    (_message.Message,),
    {
        "DESCRIPTOR": _MONEY,
        "__module__": "analyzer_pb2"
        # @@protoc_insertion_point(class_scope:evercoinx.analyzer.Money)
    },
)
_sym_db.RegisterMessage(Money)

Seat = _reflection.GeneratedProtocolMessageType(
    "Seat",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEAT,
        "__module__": "analyzer_pb2"
        # @@protoc_insertion_point(class_scope:evercoinx.analyzer.Seat)
    },
)
_sym_db.RegisterMessage(Seat)


_ANALYZER = _descriptor.ServiceDescriptor(
    name="Analyzer",
    full_name="evercoinx.analyzer.Analyzer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=703,
    serialized_end=797,
    methods=[
        _descriptor.MethodDescriptor(
            name="SendFrame",
            full_name="evercoinx.analyzer.Analyzer.SendFrame",
            index=0,
            containing_service=None,
            input_type=_FRAMEREQUEST,
            output_type=_EMPTYRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ANALYZER)

DESCRIPTOR.services_by_name["Analyzer"] = _ANALYZER

# @@protoc_insertion_point(module_scope)
